name: Push over SCP

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Getting Ready...
        run: |
          echo "Getting Ready..."
          mkdir -p ~/.ssh/
          echo "HOST *" > ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Pushing Files...
        run: |
          echo "Pushing Files..."
          sshpass -p '${{ secrets.PASS }}' scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r -P 22 /home/runner/work/VENITH.NET/jinxcade mattthetekie@${{ secrets.DEST_IP }}:/var/www/jinxcade
