name: Push files over SCP

on:
  push:
  workflow_dispatch:

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Downloading Files
        run: |
          echo Downloading Files...
          
      - name: remote ssh command
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.IP }}
          username: mattthetekie
          password : ${{ secrets.PASS }}
          script: rm -rf /usr/share/nginx/jinxcade/
      - name: Push Files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: mattthetekie
          password : ${{ secrets.PASS }}
          source: "/home/runner/work/jinxcade/jinxcade"
          target: "/usr/share/nginx/jinxcade/"
      - name: remote ssh command
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.IP }}
          username: mattthetekie
          password : ${{ secrets.PASS }}
          script: mv /var/www/jinxcade/github/workspace/* /usr/share/nginx/jinxcade/ -f
